name: CDK github action

on: [push, workflow_dispatch]

jobs:
  cdk_skill_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      
    - name: Install npm
      run: 'sudo apt update -y && sudo apt install nodejs npm -y'

    - name: Install package dependencies
      run: npm install
    
    - name: Install AWS CDK
      run: 'sudo npm install -g aws-cdk'

    - name: CDK synth
      run: cdk synth

    - name: CDK bootstrap accounts
      run: cdk bootstrap

    - name: CDK deploy skill
      run: cdk deploy --require-approval=never

    - name: Build local project
      run: npm run-script test

    - name: Testing
      run: npm run-script test
